### PR TITLE
escape log file to resolve #192 remember fix

### LINKED ISSUE #192: Need to add quotes
https://github.com/appium/appium-dotnet-driver/blob/c5cb85a1227eeb62b18b12e0a4e8234e3b449d93/appium-dotnet-driver/Appium/Service/AppiumServiceBuilder.cs#L472

should be argList.Add($"""{PathToLogFile}""");
To resolve issue when PathToLogFile have space character

### PR DESCRIPTION
**Pull request by MicMor008**
## Change list

Please provide briefly described change list which are you going to propose. 
 
## Types of changes

What types of changes are you proposing/introducing to .NET client?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Integration tests
- [ ] Have you provided integration tests to pass against the latest version of appium? (for Bugfix or New feature)

## Details

Please provide more details about changes if it is necessary. If there are new features you can provide code samples which show the way they
work and possible use cases. Also you can create [gists](https://gist.github.com) with pasted C# code samples or put them here using markdown. 
About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and [Writing on GitHub](https://help.github.com/categories/writing-on-github/)

### CODE REVIEW

File: appium-dotnet-driver/Appium/Service/AppiumServiceBuilder.cs [hunk 1]
```diff
@@ -475,7 +475,7 @@ private string Args
                 if (PathToLogFile != null)
                 {
                     argList.Add("--log");
-                    argList.Add(PathToLogFile);
+                    argList.Add($"\"{PathToLogFile}\"");
```
Comment (mykola-mokhnach) [inline appium-dotnet-driver/Appium/Service/AppiumServiceBuilder.cs]: this will simply fix the case for this particular argument. I'd say it is necessary to properly escape all arguments in the code block below: https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/
